// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5q_iiQpsDQeMIaOfLeFjPEevKCsL7VG4',
    appId: '1:347456717704:web:2bc7db9fcd9da802fdb03d',
    messagingSenderId: '347456717704',
    projectId: 'masrofy-app',
    authDomain: 'masrofy-app.firebaseapp.com',
    storageBucket: 'masrofy-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIoTHvdA8FMJZBNT3wVy1QmnRwaVZsLQg',
    appId: '1:347456717704:android:c9d8c78dfcf5297efdb03d',
    messagingSenderId: '347456717704',
    projectId: 'masrofy-app',
    storageBucket: 'masrofy-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYXWLmBzdCM-jXpl3wF9TgOpauW5ge48k',
    appId: '1:347456717704:ios:f338482ab672c9d2fdb03d',
    messagingSenderId: '347456717704',
    projectId: 'masrofy-app',
    storageBucket: 'masrofy-app.firebasestorage.app',
    iosBundleId: 'com.hany.smartplanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYXWLmBzdCM-jXpl3wF9TgOpauW5ge48k',
    appId: '1:347456717704:ios:f338482ab672c9d2fdb03d',
    messagingSenderId: '347456717704',
    projectId: 'masrofy-app',
    storageBucket: 'masrofy-app.firebasestorage.app',
    iosBundleId: 'com.hany.smartplanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5q_iiQpsDQeMIaOfLeFjPEevKCsL7VG4',
    appId: '1:347456717704:web:df4327008445a105fdb03d',
    messagingSenderId: '347456717704',
    projectId: 'masrofy-app',
    authDomain: 'masrofy-app.firebaseapp.com',
    storageBucket: 'masrofy-app.firebasestorage.app',
  );
}
